name: creo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  appinio_video_player: ^1.2.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.4
  email_auth: ^2.0.0
  file_picker: ^6.2.1
  firebase_auth: ^4.19.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  zego_uikit_prebuilt_live_streaming: ^3.8.0
  zego_uikit_prebuilt_video_conference: ^2.7.4
  zego_zimkit: ^1.18.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
